const products = [
  {
    id: 1,
    brand: "Bass Pro Shops",
    imgBrand: "https://i.imgur.com/z5HJjSZ.png",
    nameProduct: "Bass Pro Shops Red Wine ",
    price: 499,
    discount: 0,
    images: [
      "https://i.imgur.com/0C2Ae2I.jpg",
      "https://i.imgur.com/bN9XKVy.jpg",
      "https://i.imgur.com/bZ3Zo6w.jpg",
      "https://i.imgur.com/1IPFAnv.jpg",
    ],
    whatsLink: "",
  },
  {
    id: 2,
    brand: "Bass Pro Shops",
    imgBrand: "https://i.imgur.com/z5HJjSZ.png",
    nameProduct: "Bass Pro Shops Red ",
    price: 499,
    discount: 0,
    images: [
      "https://i.imgur.com/BGEpV62.jpg",
      "https://i.imgur.com/v75Kroz.jpg",
      "https://i.imgur.com/fOKoHor.jpg",
      "https://i.imgur.com/Nw8ZhWv.jpg",
    ],
    whatsLink: "",
  },
  {
    id: 3,
    brand: "Bass Pro Shops",
    imgBrand: "https://i.imgur.com/z5HJjSZ.png",
    nameProduct: "Bass Pro Shops Brown",
    price: 499,
    discount: 0,
    images: [
      "https://i.imgur.com/oz7qA8q.jpg",
      "https://i.imgur.com/J1NnRPE.jpg",
      "https://i.imgur.com/9fW7vXK.jpg",
      "https://i.imgur.com/J1NnRPE.jpg",
    ],
    whatsLink: "",
  },
  {
    id: 4,
    brand: "Bass Pro Shops",
    imgBrand: "https://i.imgur.com/z5HJjSZ.png",
    nameProduct: "Bass Pro Shops Orange",
    price: 499,
    discount: 0,
    images: [
      "https://i.imgur.com/nbw7rKN.jpg",
      "https://i.imgur.com/IsjyKrw.jpg",
      "https://i.imgur.com/fc79cjN.jpg",
      "https://i.imgur.com/fNNiqV8.jpg",
    ],
    whatsLink: "",
  },
  {
    id: 5,
    brand: "Bass Pro Shops",
    imgBrand: "https://i.imgur.com/z5HJjSZ.png",
    nameProduct: "Bass Pro Shops Blue",
    price: 499,
    discount: 0,
    images: [
      "https://i.imgur.com/IzRI0yY.jpg",
      "https://i.imgur.com/yYIFxQk.jpg",
      "https://i.imgur.com/RxhiV38.jpg",
      "https://i.imgur.com/GtxTWNs.jpg",
    ],
    whatsLink: "",
  },
  {
    id: 6,
    brand: "Bass Pro Shops",
    imgBrand: "https://i.imgur.com/z5HJjSZ.png",
    nameProduct: "Bass Pro Shops White",
    price: 499,
    discount: 0,
    images: [
      "https://i.imgur.com/JIqYPiM.jpg",
      "https://i.imgur.com/LWNT1Ho.jpg",
      "https://i.imgur.com/nHsFy4i.jpg",
      "https://i.imgur.com/H8rHl6P.jpg",
    ],
    whatsLink: "",
  },
  {
    id: 7,
    brand: "Bass Pro Shops",
    imgBrand: "https://i.imgur.com/z5HJjSZ.png",
    nameProduct: "Bass Pro Shops Black",
    price: 499,
    discount: 0,
    images: [
      "https://i.imgur.com/QPB37jw.jpg",
      "https://i.imgur.com/a0LLBhD.jpg",
      "https://i.imgur.com/T4cM5yu.jpg",
      "https://i.imgur.com/a0LLBhD.jpg",
    ],
    whatsLink: "",
  },
];
module.exports = products;
